### ISSUE TITLE
Using EnableCanvas

### ISSUE THREAD

**Issue by jminardi** [enthought/traits-enaml#62]
I am looking for a simple example of using the `EnableCanvas` widget. Here is my unsuccessful attempt:

ETS_TOOLKIT is set to qt4
enaml version: 0.8.9-1
traits_enaml version: latest master
chaco version: 4.3.0
### traits-enaml-ex.py:

``` python
import traits_enaml
from enaml.qt.qt_application import QtApplication
from chaco.api import Plot
from traits.api import HasStrictTraits, Instance

class Model(HasStrictTraits):

    plot = Instance(Plot)


if __name__ == '__main__':
    with traits_enaml.imports():
        from enable_canvas_ex import Main

    app = QtApplication()
    view = Main(model=Model())
    view.show()

    app.start()
```
### enable_canvas_ex.enaml:

``` python
from enaml.widgets.api import MainWindow, Container
from enaml.layout.api import vbox
from traits_enaml.widgets.enable_canvas import EnableCanvas



enamldef Main(MainWindow): main:
    attr model
    Container:
        constraints = [
            vbox(*widgets()),
        ]
        EnableCanvas: ecanvas:
            component = main.model.plot
```

The above files produce the following error when run:

``` bash
(Canopy 64bit) jack:~/Desktop$ python traits-enaml-ex.py 
Traceback (most recent call last):
  File "traits-enaml-ex.py", line 33, in <module>
    view.show()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/widgets/window.py", line 377, in show
    self.activate_proxy()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 206, in activate_proxy
    child.activate_proxy()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 206, in activate_proxy
    child.activate_proxy()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 203, in activate_proxy
    self.activate_top_down()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/widgets/toolkit_object.py", line 219, in activate_top_down
    self.proxy.activate_top_down()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/qt/qt_toolkit_object.py", line 76, in activate_top_down
    self.init_widget()
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/qt/qt_widget.py", line 68, in init_widget
    self.set_enabled(d.enabled)
  File "/Users/jack/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/enaml/qt/qt_widget.py", line 123, in set_enabled
    self.widget.setEnabled(enabled)
AttributeError: 'NoneType' object has no attribute 'setEnabled'
(Canopy 64bit) jack:~/Desktop$ 
```

**Comment by flyingxu** [comment]
This is the only working demo of enaml & chaco, even if the plot is empty :-)
