### ISSUE TITLE
Auto_view example not working

### ISSUE THREAD

**Issue by petrushy** [enthought/traits-enaml#74]
Hi,

The auto_view example seems not to work.

When running it gets a 
Traceback (most recent call last):
  File "auto_view.py", line 20, in <module>
    from traits_enaml.widgets.auto_view import auto_window
  File "build\bdist.win-amd64\egg\traits_enaml\widgets\auto_view.py", line 19, in <module>
    import traits_enaml
ImportError: No module named auto_editors

traits v4.5.0, enaml 0.9.8
traits-enaml from git
Python 2.7.10

Regards

**Comment by jwiggins** [comment]
What happens when you run the unit tests for traits-enaml (with `nosetests`)?

An import error for that module implies that something is going wrong in the Enaml import machinery, but right now I can't think of what might be causing that.

**Comment by petrushy** [comment]
Hi, the auto_view test  works.

__

(nosetests fails only on the opengl test)


======================================================================
ERROR: test_gl_canvas_draw (traits_enaml.tests.test_gl_canvas.GLCanvasTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\phy\Downloads\traits-enaml-master\traits-enaml-master\traits_enaml\test
s\test_gl_canvas.py", line 77, in test_gl_canvas_draw
    arr = _qimage_to_ndarray(image)
  File "C:\Users\phy\Downloads\traits-enaml-master\traits-enaml-master\traits_enaml\test
s\test_gl_canvas.py", line 94, in _qimage_to_ndarray
    return np.array(bits).reshape(height, width, 4)
ValueError: total size of new array must be unchanged
-------------------- >> begin captured logging << --------------------
OpenGL.acceleratesupport: INFO: OpenGL_accelerate module loaded
OpenGL.arrays.arraydatatype: INFO: Using accelerated ArrayDatatype
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 49 tests in 6.583s

**Comment by jwiggins** [comment]
Hmm... Stranger still. Did you install traits-enaml (with `setup.py install` or `setup.py develop`)?

**Comment by petrushy** [comment]
It works when I install it with python setup.py develop!

I have tried both directly to install it with a "install" and through a conda package (a python setup.py install in a clean environment), none of these did work.
